CREATE DATABASE Pruebas;

CREATE USER 'mickey'@'localhost' IDENTIFIED BY 'mouse';

GRANT ALL ON Pruebas.* TO 'mickey'@'localhost';

USE Pruebas;

CREATE TABLE IF NOT EXISTS Paises (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE_PAIS VARCHAR(50)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Ciudades (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE_CIUDAD VARCHAR(50),
	PAIS INT,
	FOREIGN KEY (PAIS) REFERENCES Paises(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREA
FLUSH PRIVILEGES;
